worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }

        location /health/liveness {
            return 200 'OK';
            access_log off;
        }

        location /health/readiness {
            return 200 'OK';
            access_log off;
        }
    }
}