name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'

permissions:
  # for github pages branch
  contents: write
  id-token: write
  actions: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          npm run build
          # Copy index.html to 404.html to "rewrite" all unknown routes back to index.html (when deploying to GitHub Pages)
          cp layout/build/index.html layout/build/404.html
          cp widgets/build/index.html widgets/build/404.html
          cp regional-app-1/build/index.html regional-app-1/build/404.html
          cp regional-app-2/build/index.html regional-app-2/build/404.html
        env:
          LAYOUT_URL: https://turbo-doodle-2nm87nq.pages.github.io/layout
          WIDGETS_URL: https://turbo-doodle-2nm87nq.pages.github.io/widgets
          REGIONAL_APP_1_URL: https://turbo-doodle-2nm87nq.pages.github.io/regional-app-1
          REGIONAL_APP_2_URL: https://turbo-doodle-2nm87nq.pages.github.io/regional-app-2
          REGIONAL_APP_1_APP_PATH: /regional-app-1
          REGIONAL_APP_2_APP_PATH: /regional-app-2

      - name: Setup Git Credentials
        run: |
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config --global user.email "github-actions-bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          # echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          # git config --global credential.helper store
      - name: Deploy to GitHub Pages
        run: npm run deploy-github-pages:all
        # cp dist/index.html dist/404.html
